version: "3.9"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8082:8080"
    networks:
      - springapimysql-net
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: serbo
      MYSQL_PASSWORD: Test1234!
      MYSQL_PORT: 3306
    #    - spring.datasource.url=jdbc:mysql://mysqldb:3306/demo?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    volumes:
      - appvolume:/var/lib/mysql
    ports:
      - "6606:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: serbo
      MYSQL_PASSWORD: Test1234!
      MYSQL_ROOT_PASSWORD: Test1234!
networks:
  springapimysql-net:

volumes:
  appvolume: